format_version: 10
pipelines:
  deploy:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-c948e74:
        git: https://github.com/divyansh360circle/testing.git
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          run-unit-test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - i
                command: npm
                run_if: passed
